from pydantic import BaseModel, field_validator
from typing import Optional
from datetime import datetime
from typing import Dict

AMBIENTAL_COUNT = 10000
GOVERNANCA_COUNT = 20000
SOCIAL_COUNT = 30000
CONSENT_COUNT = 40000
REGISTRATION_COUNT = 50000

class SurveyMeta(BaseModel):
    empresa: str
    atividade: str
    estado: str
    cidade: str
    producaomes: str
    unidproducao: str
    data: datetime

    @field_validator("data", mode='before')
    def validate_data(cls, value):
        try:
            return datetime.strptime(value, "%d/%m/%Y")
        except ValueError:
            raise ValueError("Invalid date format")

class SurveyClass(BaseModel):
    _name_mapping: Dict[str, int] = {"teste": 1}
    
    def get_by_id(self, id: int):
        for key, value in self._name_mapping.items():
            if value == id:
                return getattr(self, key)

class SurveyAmbiental(SurveyClass):
    _name_mapping: Dict[str, int] = {
        "ambiental_emissoesGEE": AMBIENTAL_COUNT+1,
        "ambiental_inventarioGEE": AMBIENTAL_COUNT+2,
        "ambiental_planoMitigacao": AMBIENTAL_COUNT+3,
        "ambiental_participacaoPlataformas": AMBIENTAL_COUNT+4,
        "ambiental_divulgarInventario": AMBIENTAL_COUNT+5,
        "ambiental_grupoTrabalho": AMBIENTAL_COUNT+6,
        "ambiental_identificacaoCenarios": AMBIENTAL_COUNT+7,
        "ambiental_planoAdaptacao": AMBIENTAL_COUNT+8,
        "ambiental_engajamentoStakeholders": AMBIENTAL_COUNT+9,
        "ambiental_comunicacaoPlano": AMBIENTAL_COUNT+10,
        "ambiental_diagnosticoMetas": AMBIENTAL_COUNT+11,
        "ambiental_energiaRenovavel": AMBIENTAL_COUNT+12,
        "ambiental_eficienciaEnergetica": AMBIENTAL_COUNT+13,
        "ambiental_trocaLampadas": AMBIENTAL_COUNT+14,
        "ambiental_iso50001": AMBIENTAL_COUNT+15,
        "ambiental_usoAguaSuperficial": AMBIENTAL_COUNT+16,
        "ambiental_monitoraAgua": AMBIENTAL_COUNT+17,
        "ambiental_indicadoresMetas": AMBIENTAL_COUNT+18,
        "ambiental_projetosReuso": AMBIENTAL_COUNT+19,
        "ambiental_acoesExternas": AMBIENTAL_COUNT+20,
        "ambiental_gestaoEfluentes": AMBIENTAL_COUNT+21,
        "ambiental_controlesTradicionais": AMBIENTAL_COUNT+22,
        "ambiental_praticasSustentaveis": AMBIENTAL_COUNT+23,
        "ambiental_planoefluente": AMBIENTAL_COUNT+24,
        "ambiental_gestaoEfluentesInovacoes": AMBIENTAL_COUNT+25,
        "ambiental_biodiversidadeLegais": AMBIENTAL_COUNT+26,
        "ambiental_praticasDispersas": AMBIENTAL_COUNT+27,
        "ambiental_biodiversidadeIntegradas": AMBIENTAL_COUNT+28,
        "ambiental_biodiversidadeEstrategia": AMBIENTAL_COUNT+29,
        "ambiental_biodiversidadePrioridade": AMBIENTAL_COUNT+30,
        "ambiental_usoSoloLegais": AMBIENTAL_COUNT+31,
        "ambiental_iniciativasSolo": AMBIENTAL_COUNT+32,
        "ambiental_usoSoloPraticas": AMBIENTAL_COUNT+33,
        "ambiental_usoSoloEstrategico": AMBIENTAL_COUNT+34,
        "ambiental_engajamentoSolo": AMBIENTAL_COUNT+35,
        "ambiental_economiaCircularIniciais": AMBIENTAL_COUNT+36,
        "ambiental_abordagemCicloVida": AMBIENTAL_COUNT+37,
        "ambiental_materiaisreciclados": AMBIENTAL_COUNT+38,
        "ambiental_abordagemCircularidade": AMBIENTAL_COUNT+39,
        "ambiental_parceriasEstrategicas": AMBIENTAL_COUNT+40,
        "ambiental_classificacaoResiduos": AMBIENTAL_COUNT+41,
        "ambiental_segregacaoResiduos": AMBIENTAL_COUNT+42,
        "ambiental_gestaoResiduosImplementado": AMBIENTAL_COUNT+43,
        "ambiental_logisticaReversa": AMBIENTAL_COUNT+44,
        "ambiental_avaliacaoTerceiros": AMBIENTAL_COUNT+45,
        "ambiental_SGAnaoImplementado": AMBIENTAL_COUNT+46,
        "ambiental_SGAIdentificacao": AMBIENTAL_COUNT+47,
        "ambiental_controlesOperacionais": AMBIENTAL_COUNT+48,
        "ambiental_conscientizacaoGestao": AMBIENTAL_COUNT+49,
        "ambiental_liderancaAmbiental": AMBIENTAL_COUNT+50,
        "ambiental_poluicaoSonoraLegais": AMBIENTAL_COUNT+51,
        "ambiental_monitoramentoSonoro": AMBIENTAL_COUNT+52,
        "ambiental_substituicaoRiscosSonoros": AMBIENTAL_COUNT+53,
        "ambiental_engajamentoSonoro": AMBIENTAL_COUNT+54,
        "ambiental_lideranca_sonora": AMBIENTAL_COUNT+55,
        "ambiental_gestao_ar": AMBIENTAL_COUNT+56,
        "ambiental_gestao_ar_monitoramento": AMBIENTAL_COUNT+57,
        "ambiental_gestao_ar_substituicao": AMBIENTAL_COUNT+58,
        "ambiental_gestao_ar_partes_interessadas": AMBIENTAL_COUNT+59,
        "ambiental_lideranca_qualidade_ar": AMBIENTAL_COUNT+60,
        "ambiental_gerenciamento_areas_contaminadas": AMBIENTAL_COUNT+61,
        "ambiental_gerenciamento_areas_contaminadas_monitoramento": AMBIENTAL_COUNT+62,
        "ambiental_gerenciamento_areas_contaminadas_substituicao": AMBIENTAL_COUNT+63,
        "ambiental_gerenciamento_areas_contaminadas_partes_interessadas": AMBIENTAL_COUNT+64,
        "ambiental_lideranca_areas_contaminadas": AMBIENTAL_COUNT+65,
        "ambiental_gerenciamento_produtos_perigosos": AMBIENTAL_COUNT+66,
        "ambiental_gerenciamento_produtos_perigosos_avancado": AMBIENTAL_COUNT+67,
        "ambiental_gerenciamento_produtos_perigosos_substituicao": AMBIENTAL_COUNT+68,
        "ambiental_gerenciamento_produtos_perigosos_partes_interessadas": AMBIENTAL_COUNT+69,
        "ambiental_lideranca_produtos_perigosos": AMBIENTAL_COUNT+70,
        "ambiental_uso_agua_dia": AMBIENTAL_COUNT+71,
        "ambiental_consumo_energia_mes": AMBIENTAL_COUNT+72,
        "ambiental_emissoes_gee_mes": AMBIENTAL_COUNT+73,
        "ambiental_reciclagem_residuos_mes": AMBIENTAL_COUNT+74,
    }
    ambiental_emissoesGEE: Optional[str]
    ambiental_inventarioGEE: Optional[str]
    ambiental_planoMitigacao: Optional[str]
    ambiental_participacaoPlataformas: Optional[str]
    ambiental_divulgarInventario: Optional[str]
    ambiental_grupoTrabalho: Optional[str]
    ambiental_identificacaoCenarios: Optional[str]
    ambiental_planoAdaptacao: Optional[str]
    ambiental_engajamentoStakeholders: Optional[str]
    ambiental_comunicacaoPlano: Optional[str]
    ambiental_diagnosticoMetas: Optional[str]
    ambiental_energiaRenovavel: Optional[str]
    ambiental_eficienciaEnergetica: Optional[str]
    ambiental_trocaLampadas: Optional[str]
    ambiental_iso50001: Optional[str]
    ambiental_usoAguaSuperficial: Optional[str]
    ambiental_monitoraAgua: Optional[str]
    ambiental_indicadoresMetas: Optional[str]
    ambiental_projetosReuso: Optional[str]
    ambiental_acoesExternas: Optional[str]
    ambiental_gestaoEfluentes: Optional[str]
    ambiental_controlesTradicionais: Optional[str]
    ambiental_praticasSustentaveis: Optional[str]
    ambiental_planoefluente: Optional[str]
    ambiental_gestaoEfluentesInovacoes: Optional[str]
    ambiental_biodiversidadeLegais: Optional[str]
    ambiental_praticasDispersas: Optional[str]
    ambiental_biodiversidadeIntegradas: Optional[str]
    ambiental_biodiversidadeEstrategia: Optional[str]
    ambiental_biodiversidadePrioridade: Optional[str]
    ambiental_usoSoloLegais: Optional[str]
    ambiental_iniciativasSolo: Optional[str]
    ambiental_usoSoloPraticas: Optional[str]
    ambiental_usoSoloEstrategico: Optional[str]
    ambiental_engajamentoSolo: Optional[str]
    ambiental_economiaCircularIniciais: Optional[str]
    ambiental_abordagemCicloVida: Optional[str]
    ambiental_materiaisreciclados: Optional[str]
    ambiental_abordagemCircularidade: Optional[str]
    ambiental_parceriasEstrategicas: Optional[str]
    ambiental_classificacaoResiduos: Optional[str]
    ambiental_segregacaoResiduos: Optional[str]
    ambiental_gestaoResiduosImplementado: Optional[str]
    ambiental_logisticaReversa: Optional[str]
    ambiental_avaliacaoTerceiros: Optional[str]
    ambiental_SGAnaoImplementado: Optional[str]
    ambiental_SGAIdentificacao: Optional[str]
    ambiental_controlesOperacionais: Optional[str]
    ambiental_conscientizacaoGestao: Optional[str]
    ambiental_liderancaAmbiental: Optional[str]
    ambiental_poluicaoSonoraLegais: Optional[str]
    ambiental_monitoramentoSonoro: Optional[str]
    ambiental_substituicaoRiscosSonoros: Optional[str]
    ambiental_engajamentoSonoro: Optional[str]
    ambiental_lideranca_sonora: Optional[str]
    ambiental_gestao_ar: Optional[str]
    ambiental_gestao_ar_monitoramento: Optional[str]
    ambiental_gestao_ar_substituicao: Optional[str]
    ambiental_gestao_ar_partes_interessadas: Optional[str]
    ambiental_lideranca_qualidade_ar: Optional[str]
    ambiental_gerenciamento_areas_contaminadas: Optional[str]
    ambiental_gerenciamento_areas_contaminadas_monitoramento: Optional[str]
    ambiental_gerenciamento_areas_contaminadas_substituicao: Optional[str]
    ambiental_gerenciamento_areas_contaminadas_partes_interessadas: Optional[str]
    ambiental_lideranca_areas_contaminadas: Optional[str]
    ambiental_gerenciamento_produtos_perigosos: Optional[str]
    ambiental_gerenciamento_produtos_perigosos_avancado: Optional[str]
    ambiental_gerenciamento_produtos_perigosos_substituicao: Optional[str]
    ambiental_gerenciamento_produtos_perigosos_partes_interessadas: Optional[str]
    ambiental_lideranca_produtos_perigosos: Optional[str]
    ambiental_uso_agua_dia: float
    ambiental_consumo_energia_mes: float
    ambiental_emissoes_gee_mes: float
    ambiental_reciclagem_residuos_mes: float

    @field_validator(
        "ambiental_uso_agua_dia",
        "ambiental_consumo_energia_mes",
        "ambiental_emissoes_gee_mes",
        "ambiental_reciclagem_residuos_mes",
        mode='before'
    )
    def validate_float(cls, value):
        try:
            return float(value)
        except ValueError:
            raise ValueError("Invalid float format")

class SurveyGovernanca(SurveyClass):
    _name_mapping: Dict[str, int] = {
        "documentos_essenciais": GOVERNANCA_COUNT+1,
        "estatuto_diretrizes": GOVERNANCA_COUNT+2,
        "praticas_recomendadas": GOVERNANCA_COUNT+3,
        "politicas_selecao_remuneracao": GOVERNANCA_COUNT+4,
        "diretrizes_governanca_compliance": GOVERNANCA_COUNT+5,
        "comite_esg": GOVERNANCA_COUNT+6,
        "planejamento_acoes_esg": GOVERNANCA_COUNT+7,
        "objetivos_metas_esg": GOVERNANCA_COUNT+8,
        "adesao_pacto_global": GOVERNANCA_COUNT+9,
        "adocao_ods": GOVERNANCA_COUNT+10,
        "codigo_conduta": GOVERNANCA_COUNT+11,
        "comite_compliance": GOVERNANCA_COUNT+12,
        "monitoramento_compliance": GOVERNANCA_COUNT+13,
        "sistema_denuncias": GOVERNANCA_COUNT+14,
        "due_diligence": GOVERNANCA_COUNT+15,
        "combate_concorrencia_desleal": GOVERNANCA_COUNT+16,
        "mapeamento_concorrentes": GOVERNANCA_COUNT+17,
        "mapeamento_concorrentes_politica": GOVERNANCA_COUNT+18,
        "mapeamento_concorrentes_analise": GOVERNANCA_COUNT+19,
        "mapeamento_concorrentes_classificacao": GOVERNANCA_COUNT+20,
        "identificacao_partes_interessadas_nao_estruturada": GOVERNANCA_COUNT+21,
        "identificacao_partes_interessadas_cuidadosa": GOVERNANCA_COUNT+22,
        "partes_interessadas_detalhada": GOVERNANCA_COUNT+23,
        "partes_interessadas_continua": GOVERNANCA_COUNT+24,
        "partes_interessadas_sustentabilidade": GOVERNANCA_COUNT+25,
        "gestao_riscos_basica": GOVERNANCA_COUNT+26,
        "identificacao_riscos_fundamental": GOVERNANCA_COUNT+27,
        "analise_riscos_priorizacao": GOVERNANCA_COUNT+28,
        "planos_acao_riscos": GOVERNANCA_COUNT+29,
        "transparencia_riscos": GOVERNANCA_COUNT+30,
        "controles_internos_basicos": GOVERNANCA_COUNT+31,
        "controles_internos_sistematicos": GOVERNANCA_COUNT+32,
        "controles_internos_robusto": GOVERNANCA_COUNT+33,
        "controles_internos_preventivas": GOVERNANCA_COUNT+34,
        "controles_internos_preventivas_contas": GOVERNANCA_COUNT+35,
        "auditorias_basicas_ESG": GOVERNANCA_COUNT+36,
        "auditoria_requisitos_ESG": GOVERNANCA_COUNT+37,
        "auditorias_atuacao_direcao_ESG": GOVERNANCA_COUNT+38,
        "auditorias_plano_acao_ESG": GOVERNANCA_COUNT+39,
        "auditorias_transparencia_ESG": GOVERNANCA_COUNT+40,
        "avaliacao_conformidade": GOVERNANCA_COUNT+41,
        "planos_acao_estrategicos": GOVERNANCA_COUNT+42,
        "monitoramento_multas": GOVERNANCA_COUNT+43,
        "programas_compliance": GOVERNANCA_COUNT+44,
        "tendencias": GOVERNANCA_COUNT+45,
        "procedimentos_basicos": GOVERNANCA_COUNT+46,
        "acoes_isoladas": GOVERNANCA_COUNT+47,
        "acoes_integradas": GOVERNANCA_COUNT+48,
        "politica_estruturada": GOVERNANCA_COUNT+49,
        "politica_externa": GOVERNANCA_COUNT+50,
        "privacidade_basica": GOVERNANCA_COUNT+51,
        "acoes_privacidade_isoladas": GOVERNANCA_COUNT+52,
        "acoes_privacidade_integradas": GOVERNANCA_COUNT+53,
        "politica_privacidade": GOVERNANCA_COUNT+54,
        "politica_privacidade_externa": GOVERNANCA_COUNT+55,
        "responsabilizacao_basica": GOVERNANCA_COUNT+56,
        "prestacao_contas_transparente": GOVERNANCA_COUNT+57,
        "prestacao_contas_detalhada": GOVERNANCA_COUNT+58,
        "prestacao_contas_planejamento": GOVERNANCA_COUNT+59,
        "prestacao_contas_completa": GOVERNANCA_COUNT+60,
        "informacoes_esg_isoladas": GOVERNANCA_COUNT+61,
        "relatorio_esg_basico": GOVERNANCA_COUNT+62,
        "relatorio_esg_adequado": GOVERNANCA_COUNT+63,
        "relatorio_esg_detalhado": GOVERNANCA_COUNT+64,
        "relatorio_esg_verificacoes": GOVERNANCA_COUNT+65,
        "conselho_indep": GOVERNANCA_COUNT+66,
        "conselho_mulher": GOVERNANCA_COUNT+67,
        "conselho_negra": GOVERNANCA_COUNT+68,
    }
    documentos_essenciais: Optional[str]
    estatuto_diretrizes: Optional[str]
    praticas_recomendadas: Optional[str]
    politicas_selecao_remuneracao: Optional[str]
    diretrizes_governanca_compliance: Optional[str]
    comite_esg: Optional[str]
    planejamento_acoes_esg: Optional[str]
    objetivos_metas_esg: Optional[str]
    adesao_pacto_global: Optional[str]
    adocao_ods: Optional[str]
    codigo_conduta: Optional[str]
    comite_compliance: Optional[str]
    monitoramento_compliance: Optional[str]
    sistema_denuncias: Optional[str]
    due_diligence: Optional[str]
    combate_concorrencia_desleal: Optional[str]
    mapeamento_concorrentes: Optional[str]
    mapeamento_concorrentes_politica: Optional[str]
    mapeamento_concorrentes_analise: Optional[str]
    mapeamento_concorrentes_classificacao: Optional[str]
    identificacao_partes_interessadas_nao_estruturada: Optional[str]
    identificacao_partes_interessadas_cuidadosa: Optional[str]
    partes_interessadas_detalhada: Optional[str]
    partes_interessadas_continua: Optional[str]
    partes_interessadas_sustentabilidade: Optional[str]
    gestao_riscos_basica: Optional[str]
    identificacao_riscos_fundamental: Optional[str]
    analise_riscos_priorizacao: Optional[str]
    planos_acao_riscos: Optional[str]
    transparencia_riscos: Optional[str]
    controles_internos_basicos: Optional[str]
    controles_internos_sistematicos: Optional[str]
    controles_internos_robusto: Optional[str]
    controles_internos_preventivas: Optional[str]
    controles_internos_preventivas_contas: Optional[str]
    auditorias_basicas_ESG: Optional[str]
    auditoria_requisitos_ESG: Optional[str]
    auditorias_atuacao_direcao_ESG: Optional[str]
    auditorias_plano_acao_ESG: Optional[str]
    auditorias_transparencia_ESG: Optional[str]
    avaliacao_conformidade: Optional[str]
    planos_acao_estrategicos: Optional[str]
    monitoramento_multas: Optional[str]
    programas_compliance: Optional[str]
    tendencias: Optional[str]
    procedimentos_basicos: Optional[str]
    acoes_isoladas: Optional[str]
    acoes_integradas: Optional[str]
    politica_estruturada: Optional[str]
    politica_externa: Optional[str]
    privacidade_basica: Optional[str]
    acoes_privacidade_isoladas: Optional[str]
    acoes_privacidade_integradas: Optional[str]
    politica_privacidade: Optional[str]
    politica_privacidade_externa: Optional[str]
    responsabilizacao_basica: Optional[str]
    prestacao_contas_transparente: Optional[str]
    prestacao_contas_detalhada: Optional[str]
    prestacao_contas_planejamento: Optional[str]
    prestacao_contas_completa: Optional[str]
    informacoes_esg_isoladas: Optional[str]
    relatorio_esg_basico: Optional[str]
    relatorio_esg_adequado: Optional[str]
    relatorio_esg_detalhado: Optional[str]
    relatorio_esg_verificacoes: Optional[str]
    conselho_indep: Optional[str]
    conselho_mulher: Optional[str]
    conselho_negra: Optional[str]

class SurveySocial(SurveyClass):
    _name_mapping: Dict[str, int] = {
        "mapeamento_sociedade_civil": SOCIAL_COUNT+1,
        "incentivo_doacoes": SOCIAL_COUNT+2,
        "disponibilizacao_recursos": SOCIAL_COUNT+3,
        "disponibilizacao_bolsas": SOCIAL_COUNT+4,
        "indicadores_isp": SOCIAL_COUNT+5,
        "plano_comunicacao": SOCIAL_COUNT+6,
        "pesquisas_stakeholders": SOCIAL_COUNT+7,
        "indicadores_metas": SOCIAL_COUNT+8,
        "engajamento_social": SOCIAL_COUNT+9,
        "fomento_comunicacao": SOCIAL_COUNT+10,
        "participacao_comunidade": SOCIAL_COUNT+11,
        "identificacao_formadores": SOCIAL_COUNT+12,
        "plano_estrategico": SOCIAL_COUNT+13,
        "capacitacao_comunidade": SOCIAL_COUNT+14,
        "prioridade_fornecedores": SOCIAL_COUNT+15,
        "iniciativas_dh": SOCIAL_COUNT+16,
        "abordagem_reativa_dh": SOCIAL_COUNT+17,
        "abordagem_proativa_dh": SOCIAL_COUNT+18,
        "abordagem_proativa_dh_metas": SOCIAL_COUNT+19,
        "abordagem_proativa_dh_integracao": SOCIAL_COUNT+20,
        "legislacao_trabalhista_combate_trabalho_forcado": SOCIAL_COUNT+21,
        "legislacao_trabalhista_oit": SOCIAL_COUNT+22,
        "legislacao_trabalhista_oit_avaliacao": SOCIAL_COUNT+23,
        "legislacao_trabalhista_oit_monitoramento": SOCIAL_COUNT+24,
        "legislacao_trabalhista_oit_monitoramento_treinamento": SOCIAL_COUNT+25,
        "trabalho_infantil": SOCIAL_COUNT+26,
        "mapeamento_trabalho_infantil": SOCIAL_COUNT+27,
        "sistema_gestao_trabalho_infantil": SOCIAL_COUNT+28,
        "clausulas_trabalho_infantil": SOCIAL_COUNT+29,
        "campanhas_publicas_trabalho_infantil": SOCIAL_COUNT+30,
        "diversidade_equidade": SOCIAL_COUNT+31,
        "diversidade_equidade_formal": SOCIAL_COUNT+32,
        "politicas_diversidade_equidade": SOCIAL_COUNT+33,
        "politicas_diversidade_equidade_estrategias": SOCIAL_COUNT+34,
        "comunicacao_diversidade_equidade": SOCIAL_COUNT+35,
        "inclusao": SOCIAL_COUNT+36,
        "lideranca_inclusao": SOCIAL_COUNT+37,
        "politica_inclusao": SOCIAL_COUNT+38,
        "programa_diversidade": SOCIAL_COUNT+39,
        "programa_afirmativas": SOCIAL_COUNT+40,
        "desenvolvimento_profissional": SOCIAL_COUNT+41,
        "desenvolvimento_profissional_acoes": SOCIAL_COUNT+42,
        "politica_desenvolvimento_profissional": SOCIAL_COUNT+43,
        "programa_desenvolvimento_profissional": SOCIAL_COUNT+44,
        "politica_desenvolvimento_comunidade": SOCIAL_COUNT+45,
        "requisitos_legais": SOCIAL_COUNT+46,
        "analise_riscos_sso": SOCIAL_COUNT+47,
        "conscientizacao_forca_trabalho": SOCIAL_COUNT+48,
        "participacao_sso": SOCIAL_COUNT+49,
        "protagonismo_sso": SOCIAL_COUNT+50,
        "iniciativas_qualidade_vida": SOCIAL_COUNT+51,
        "acoes_pontuais_qualidade_vida": SOCIAL_COUNT+52,
        "participacao_trabalhadores": SOCIAL_COUNT+53,
        "programa_acompanhamento": SOCIAL_COUNT+54,
        "formacao_lideres": SOCIAL_COUNT+55,
        "legislacao_liberdade_associacao": SOCIAL_COUNT+56,
        "apoio_organizacoes_representativas": SOCIAL_COUNT+57,
        "dialogo_entidades_representativas": SOCIAL_COUNT+58,
        "abordagem_proativa": SOCIAL_COUNT+59,
        "resultados_interacoes": SOCIAL_COUNT+60,
        "iniciativas_basicas_politica": SOCIAL_COUNT+61,
        "nova_politica_remuneracao": SOCIAL_COUNT+62,
        "politica_remuneracao_implementada": SOCIAL_COUNT+63,
        "praticas_remuneracao_equitativas": SOCIAL_COUNT+64,
        "politica_remuneracao_estrategico": SOCIAL_COUNT+65,
        "requisitos_legais_direitos_consumidor": SOCIAL_COUNT+66,
        "postura_transparente": SOCIAL_COUNT+67,
        "canais_comunicacao_abertos": SOCIAL_COUNT+68,
        "desenvolvimento_produtos_sustentaveis": SOCIAL_COUNT+69,
        "protagonismo_relacoes_clientes": SOCIAL_COUNT+70,
        "politica_relacionamento_fornecedores": SOCIAL_COUNT+71,
        "comunicacao_ativa_fornecedores": SOCIAL_COUNT+72,
        "processo_qualificacao_fornecedores": SOCIAL_COUNT+73,
        "politica_monitoramento_fornecedores": SOCIAL_COUNT+74,
        "incentivo_fornecedores_protagonismo": SOCIAL_COUNT+75,
        "h_treinamento_func_ano": SOCIAL_COUNT+76,
        "taxa_rotativ": SOCIAL_COUNT+77,
        "diver_genero_anual": SOCIAL_COUNT+78,
        "acid_trab_anual_horacolab": SOCIAL_COUNT+79,
        "afast_trab_anual_horacolab": SOCIAL_COUNT+80,
        "capac_fornecedor_socioamb_porcent": SOCIAL_COUNT+81,
        "invest_desenv_comunid_reais": SOCIAL_COUNT+82,
    }
    mapeamento_sociedade_civil: Optional[str]
    incentivo_doacoes: Optional[str]
    disponibilizacao_recursos: Optional[str]
    disponibilizacao_bolsas: Optional[str]
    indicadores_isp: Optional[str]
    plano_comunicacao: Optional[str]
    pesquisas_stakeholders: Optional[str]
    indicadores_metas: Optional[str]
    engajamento_social: Optional[str]
    fomento_comunicacao: Optional[str]
    participacao_comunidade: Optional[str]
    identificacao_formadores: Optional[str]
    plano_estrategico: Optional[str]
    capacitacao_comunidade: Optional[str]
    prioridade_fornecedores: Optional[str]
    iniciativas_dh: Optional[str]
    abordagem_reativa_dh: Optional[str]
    abordagem_proativa_dh: Optional[str]
    abordagem_proativa_dh_metas: Optional[str]
    abordagem_proativa_dh_integracao: Optional[str]
    legislacao_trabalhista_combate_trabalho_forcado: Optional[str]
    legislacao_trabalhista_oit: Optional[str]
    legislacao_trabalhista_oit_avaliacao: Optional[str]
    legislacao_trabalhista_oit_monitoramento: Optional[str]
    legislacao_trabalhista_oit_monitoramento_treinamento: Optional[str]
    trabalho_infantil: Optional[str]
    mapeamento_trabalho_infantil: Optional[str]
    sistema_gestao_trabalho_infantil: Optional[str]
    clausulas_trabalho_infantil: Optional[str]
    campanhas_publicas_trabalho_infantil: Optional[str]
    diversidade_equidade: Optional[str]
    diversidade_equidade_formal: Optional[str]
    politicas_diversidade_equidade: Optional[str]
    politicas_diversidade_equidade_estrategias: Optional[str]
    comunicacao_diversidade_equidade: Optional[str]
    inclusao: Optional[str]
    lideranca_inclusao: Optional[str]
    politica_inclusao: Optional[str]
    programa_diversidade: Optional[str]
    programa_afirmativas: Optional[str]
    desenvolvimento_profissional: Optional[str]
    desenvolvimento_profissional_acoes: Optional[str]
    politica_desenvolvimento_profissional: Optional[str]
    programa_desenvolvimento_profissional: Optional[str]
    politica_desenvolvimento_comunidade: Optional[str]
    requisitos_legais: Optional[str]
    analise_riscos_sso: Optional[str]
    conscientizacao_forca_trabalho: Optional[str]
    participacao_sso: Optional[str]
    protagonismo_sso: Optional[str]
    iniciativas_qualidade_vida: Optional[str]
    acoes_pontuais_qualidade_vida: Optional[str]
    participacao_trabalhadores: Optional[str]
    programa_acompanhamento: Optional[str]
    formacao_lideres: Optional[str]
    legislacao_liberdade_associacao: Optional[str]
    apoio_organizacoes_representativas: Optional[str]
    dialogo_entidades_representativas: Optional[str]
    abordagem_proativa: Optional[str]
    resultados_interacoes: Optional[str]
    iniciativas_basicas_politica: Optional[str]
    nova_politica_remuneracao: Optional[str]
    politica_remuneracao_implementada: Optional[str]
    praticas_remuneracao_equitativas: Optional[str]
    politica_remuneracao_estrategico: Optional[str]
    requisitos_legais_direitos_consumidor: Optional[str]
    postura_transparente: Optional[str]
    canais_comunicacao_abertos: Optional[str]
    desenvolvimento_produtos_sustentaveis: Optional[str]
    protagonismo_relacoes_clientes: Optional[str]
    politica_relacionamento_fornecedores: Optional[str]
    comunicacao_ativa_fornecedores: Optional[str]
    processo_qualificacao_fornecedores: Optional[str]
    politica_monitoramento_fornecedores: Optional[str]
    incentivo_fornecedores_protagonismo: Optional[str]
    h_treinamento_func_ano: Optional[str]
    taxa_rotativ: Optional[str]
    diver_genero_anual: Optional[str]
    acid_trab_anual_horacolab: Optional[str]
    afast_trab_anual_horacolab: Optional[str]
    capac_fornecedor_socioamb_porcent: Optional[str]
    invest_desenv_comunid_reais: Optional[str]

class Survey(BaseModel):
    meta: SurveyMeta
    ambiental: SurveyAmbiental
    governanca: SurveyGovernanca
    social: SurveySocial
